// Interface strings. Lesson content carries its own translations.

import type { L } from "../content/types";

export const ui = {
  learn: { en: "Learn", hi: "Seekho" },
  practice: { en: "Practice", hi: "Practice" },
  labs: { en: "Labs", hi: "Labs" },
  reference: { en: "Reference", hi: "Reference" },
  search: { en: "Search lessons, terms, commands", hi: "Lessons, terms, commands search karo" },
  language: { en: "Language", hi: "Bhasha" },
  lessons: { en: "lessons", hi: "lessons" },
  minutes: { en: "min", hi: "min" },
  module: { en: "Module", hi: "Module" },
  lesson: { en: "Lesson", hi: "Lesson" },
  start: { en: "Start with lesson 0.1", hi: "Lesson 0.1 se shuru karo" },
  continue: { en: "Continue", hi: "Wahi se continue karo" },
  completed: { en: "Completed", hi: "Complete ho gaya" },
  markComplete: { en: "Mark lesson complete", hi: "Lesson complete mark karo" },
  markIncomplete: { en: "Mark as not complete", hi: "Incomplete mark karo" },
  next: { en: "Next", hi: "Agla" },
  previous: { en: "Previous", hi: "Pichhla" },
  youWillBeAble: { en: "After this lesson you can", hi: "Is lesson ke baad tum yeh kar paoge" },
  animation: { en: "See it happen", hi: "Hote hue dekho" },
  watch: { en: "Watch", hi: "Video dekho" },
  commands: { en: "Commands in this lesson", hi: "Is lesson ke commands" },
  terms: { en: "Key terms", hi: "Key terms" },
  mistakes: { en: "Common mistakes and exam traps", hi: "Aam galtiyan aur exam traps" },
  recap: { en: "Recap", hi: "Recap" },
  lab: { en: "Try it yourself", hi: "Khud karke dekho" },
  quiz: { en: "Check yourself", hi: "Khud ko check karo" },
  onThisPage: { en: "On this page", hi: "Is page par" },
  loading: { en: "Loading…", hi: "Load ho raha hai…" },
  notWritten: { en: "This lesson is still being written.", hi: "Yeh lesson abhi likha ja raha hai." },
  english: { en: "English", hi: "English" },
  hindi: { en: "Hindi", hi: "Hindi" },
  openOnYoutube: { en: "Open on YouTube", hi: "YouTube par kholo" },
  play: { en: "Play", hi: "Play" },
  pause: { en: "Pause", hi: "Pause" },
  restart: { en: "Restart", hi: "Shuru se" },
  step: { en: "Step", hi: "Step" },
  of: { en: "of", hi: "mein se" },
  speed: { en: "Speed", hi: "Speed" },
  replayStep: { en: "Replay this step", hi: "Yeh step dobara chalao" },
  score: { en: "Score", hi: "Score" },
  tryAgain: { en: "Try again", hi: "Dobara try karo" },
  correct: { en: "Correct", hi: "Sahi" },
  notQuite: { en: "Not quite", hi: "Galat" },
  checkAnswers: { en: "Check answers", hi: "Answers check karo" },
  progress: { en: "Your progress", hi: "Tumhari progress" },
  resetProgress: { en: "Reset progress", hi: "Progress reset karo" },
} satisfies Record<string, L>;
