import type { TopologyScene } from "../types.ts";

const pathColumns = ["Switch", "Tier", "What it does"];

const scene: TopologyScene = {
  kind: "topology",
  id: "lan-architectures",
  title: { en: "Three-tier campus, collapsed core and spine-leaf", hi: "Three-tier campus, collapsed core aur spine-leaf" },
  height: 560,
  nodes: [
    { id: "edge", kind: "router", x: 400, y: 55, label: "Edge-R1" },
    { id: "inet", kind: "internet", x: 620, y: 55, label: "Internet" },
    { id: "core1", kind: "l3switch", x: 230, y: 160, label: "Core1" },
    { id: "core2", kind: "l3switch", x: 570, y: 160, label: "Core2" },
    { id: "dist1", kind: "l3switch", x: 110, y: 270, label: "Dist1" },
    { id: "dist2", kind: "l3switch", x: 290, y: 270, label: "Dist2" },
    { id: "dist3", kind: "l3switch", x: 510, y: 270, label: "Dist3" },
    { id: "dist4", kind: "l3switch", x: 690, y: 270, label: "Dist4" },
    { id: "acc1", kind: "switch", x: 110, y: 380, label: "Acc1" },
    { id: "acc2", kind: "switch", x: 290, y: 380, label: "Acc2" },
    { id: "acc3", kind: "switch", x: 510, y: 380, label: "Acc3" },
    { id: "acc4", kind: "switch", x: 690, y: 380, label: "Acc4" },
    { id: "pca", kind: "pc", x: 110, y: 485, label: "PC-A", sub: "10.1.10.10/24" },
    { id: "pcb", kind: "pc", x: 290, y: 485, label: "PC-B", sub: "10.1.20.20/24" },
    { id: "pcc", kind: "pc", x: 690, y: 485, label: "PC-C", sub: "10.2.30.30/24" },
  ],
  links: [
    { id: "l-e-inet", a: "edge", b: "inet" },
    { id: "l-e-c1", a: "edge", b: "core1", style: "fiber" },
    { id: "l-e-c2", a: "edge", b: "core2", style: "fiber" },
    { id: "l-c1-c2", a: "core1", b: "core2", style: "fiber" },
    { id: "l-d1-c1", a: "dist1", b: "core1", style: "fiber" },
    { id: "l-d1-c2", a: "dist1", b: "core2", style: "fiber" },
    { id: "l-d2-c1", a: "dist2", b: "core1", style: "fiber" },
    { id: "l-d2-c2", a: "dist2", b: "core2", style: "fiber" },
    { id: "l-d3-c1", a: "dist3", b: "core1", style: "fiber" },
    { id: "l-d3-c2", a: "dist3", b: "core2", style: "fiber" },
    { id: "l-d4-c1", a: "dist4", b: "core1", style: "fiber" },
    { id: "l-d4-c2", a: "dist4", b: "core2", style: "fiber" },
    { id: "l-d1-d2", a: "dist1", b: "dist2", style: "fiber" },
    { id: "l-d3-d4", a: "dist3", b: "dist4", style: "fiber" },
    { id: "l-a1-d1", a: "acc1", b: "dist1", style: "fiber" },
    { id: "l-a1-d2", a: "acc1", b: "dist2", style: "fiber" },
    { id: "l-a2-d1", a: "acc2", b: "dist1", style: "fiber" },
    { id: "l-a2-d2", a: "acc2", b: "dist2", style: "fiber" },
    { id: "l-a3-d3", a: "acc3", b: "dist3", style: "fiber" },
    { id: "l-a3-d4", a: "acc3", b: "dist4", style: "fiber" },
    { id: "l-a4-d3", a: "acc4", b: "dist3", style: "fiber" },
    { id: "l-a4-d4", a: "acc4", b: "dist4", style: "fiber" },
    { id: "l-pca", a: "pca", b: "acc1", bPort: "Gi1/0/5" },
    { id: "l-pcb", a: "pcb", b: "acc2", bPort: "Gi1/0/7" },
    { id: "l-pcc", a: "pcc", b: "acc4", bPort: "Gi1/0/3" },
  ],
  steps: [
    {
      title: { en: "One campus, three tiers", hi: "Ek campus, teen tiers" },
      text: {
        en: "Building A is on the left (Dist1, Dist2, Acc1, Acc2), building B on the right (Dist3, Dist4, Acc3, Acc4). Access switches uplink to their building's distribution pair, both pairs uplink to the core pair, and the core pair connects to Edge-R1, which leads out to the internet.",
        hi: "Left mein building A hai (Dist1, Dist2, Acc1, Acc2), right mein building B (Dist3, Dist4, Acc3, Acc4). Access switches apni building ke distribution pair se uplink karte hain, dono pairs core pair se, aur core pair Edge-R1 se juda hai, jo internet tak le jaata hai.",
      },
      focus: ["core1", "core2", "dist1", "dist2", "dist3", "dist4", "acc1", "acc2", "acc3", "acc4"],
    },
    {
      title: { en: "Access: where hosts plug in", hi: "Access: yahan hosts lagte hain" },
      text: {
        en: "PCs, phones, printers and APs connect only to access switches. This is where you get many ports, PoE, and per-port protection such as port security. Each access switch has two uplinks, one to each distribution switch, so one broken uplink never cuts users off.",
        hi: "PCs, phones, printers aur APs sirf access switches se connect hote hain. Yahan bahut saare ports, PoE, aur har port ki security jaise port security milti hai. Har access switch ke do uplinks hain, har distribution switch ko ek, toh ek uplink toote tab bhi users cut off nahi hote.",
      },
      focus: ["acc1", "acc2", "acc3", "acc4", "pca", "pcb", "pcc"],
    },
    {
      title: { en: "Distribution: gateways and aggregation", hi: "Distribution: gateways aur aggregation" },
      text: {
        en: "Dist1 and Dist2 collect building A's access uplinks. Layer 2 ends here: they are the default gateways for building A's subnets, like 10.1.10.1 for PC-A. Dist1's table shows its two local subnets and one summary route for all of building B.",
        hi: "Dist1 aur Dist2 building A ke access uplinks ko ikattha karte hain. Layer 2 yahin khatam hota hai: yeh building A ke subnets ke default gateway hain, jaise PC-A ke liye 10.1.10.1. Dist1 ki table mein uske do local subnets hain aur poori building B ke liye ek summary route.",
      },
      focus: ["dist1", "dist2", "dist3", "dist4"],
      badges: [{ node: "dist1", text: "GW 10.1.10.1", tone: "blue" }],
      tables: [
        {
          node: "dist1",
          title: "Dist1 routes",
          columns: ["Destination", "Next hop"],
          rows: [
            ["10.1.10.0/24", "connected"],
            ["10.1.20.0/24", "connected"],
            ["10.2.0.0/16", "Core1, Core2"],
            ["0.0.0.0/0", "Core1, Core2"],
          ],
        },
      ],
    },
    {
      title: { en: "Core: the fast backbone", hi: "Core: fast backbone" },
      text: {
        en: "Core1 and Core2 only connect distribution blocks to each other and to the edge. No hosts, no per-port features, no heavy filtering: their job is to forward fast and stay up. Every link to and between them is a routed (Layer 3) link.",
        hi: "Core1 aur Core2 sirf distribution blocks ko aapas mein aur edge se jodte hain. Na hosts, na per-port features, na heavy filtering: inka kaam hai fast forward karna aur hamesha up rehna. Inke saare links routed (Layer 3) links hain.",
      },
      focus: ["core1", "core2"],
      badges: [{ node: "dist1", text: "" }],
    },
    {
      title: { en: "Same building: routed at distribution", hi: "Same building: distribution par route" },
      text: {
        en: "PC-A (10.1.10.10) sends to PC-B (10.1.20.20), a different subnet in the same building. The frame goes up to PC-A's gateway on Dist1, which routes the packet straight back down through Acc2. The core never sees traffic that stays inside one building.",
        hi: "PC-A (10.1.10.10) PC-B (10.1.20.20) ko bhejta hai, jo same building ka doosra subnet hai. Frame upar Dist1 par PC-A ke gateway tak jaata hai, aur Dist1 packet ko route karke seedha Acc2 se neeche bhej deta hai. Jo traffic ek building ke andar rehta hai, woh core tak jaata hi nahi.",
      },
      packets: [{ path: ["pca", "acc1", "dist1", "acc2", "pcb"], label: "To 10.1.20.20", tone: "blue" }],
    },
    {
      title: { en: "Other building: up to the core and down", hi: "Doosri building: core tak upar, phir neeche" },
      text: {
        en: "PC-C (10.2.30.30) is in building B. Dist1 matches 10.2.0.0/16 and routes to Core1 (Core2 is an equal path), Core1 routes to Dist4, and Dist4 delivers into PC-C's subnet through Acc4. Five switches: access, distribution, core, distribution, access.",
        hi: "PC-C (10.2.30.30) building B mein hai. Dist1 10.2.0.0/16 match karta hai aur Core1 ko route karta hai (Core2 bhi utna hi achha path hai), Core1 Dist4 ko route karta hai, aur Dist4 Acc4 ke through PC-C ke subnet mein deliver karta hai. Paanch switches: access, distribution, core, distribution, access.",
      },
      packets: [{ path: ["pca", "acc1", "dist1", "core1", "dist4", "acc4", "pcc"], label: "To 10.2.30.30", tone: "blue" }],
      tables: [
        {
          node: "pca",
          title: "PC-A → PC-C path",
          columns: pathColumns,
          rows: [
            ["Acc1", "access", "switches frame up"],
            ["Dist1", "distribution", "routes to core"],
            ["Core1", "core", "routes to Dist4"],
            ["Dist4", "distribution", "routes to PC-C subnet"],
            ["Acc4", "access", "switches to PC-C"],
          ],
        },
      ],
    },
    {
      title: { en: "North-south vs east-west", hi: "North-south vs east-west" },
      text: {
        en: "PC-A opening a website sends traffic north-south: up through the core and out through Edge-R1. The last two steps were east-west: host to host inside the network. Campus users mostly send north-south traffic; data center servers mostly talk east-west.",
        hi: "PC-A jab website kholta hai toh traffic north-south jaata hai: core se upar aur Edge-R1 se bahar. Pichhle do steps east-west the: network ke andar host se host. Campus users ka traffic zyadatar north-south hota hai; data center ke servers zyadatar east-west baat karte hain.",
      },
      packets: [{ path: ["pca", "acc1", "dist1", "core1", "edge", "inet"], label: "To website", tone: "orange" }],
      tables: [{ node: "pca", title: "PC-A → PC-C path", columns: pathColumns, rows: [] }],
    },
    {
      title: { en: "A link fails, the path moves", hi: "Link fail hua, path badal gaya" },
      text: {
        en: "The Dist1–Core1 link goes down. Dist1 removes Core1 as a next hop and sends everything through Core2. PC-C is still reachable; only the path changed. This is why every access and distribution switch has two uplinks.",
        hi: "Dist1–Core1 link down ho jaata hai. Dist1 Core1 ko next hop se hata deta hai aur sab kuch Core2 se bhejta hai. PC-C abhi bhi reachable hai; sirf path badla. Isi liye har access aur distribution switch ke do uplinks hote hain.",
      },
      links: [{ id: "l-d1-c1", state: "down", note: "failed" }],
      packets: [{ path: ["pca", "acc1", "dist1", "core2", "dist4", "acc4", "pcc"], label: "To 10.2.30.30", tone: "blue" }],
      tables: [
        {
          node: "dist1",
          title: "Dist1 routes",
          columns: ["Destination", "Next hop"],
          rows: [
            ["10.1.10.0/24", "connected"],
            ["10.1.20.0/24", "connected"],
            ["10.2.0.0/16", "Core2"],
            ["0.0.0.0/0", "Core2"],
          ],
          hl: [2, 3],
        },
        {
          node: "pca",
          title: "PC-A → PC-C path",
          columns: pathColumns,
          rows: [
            ["Acc1", "access", "switches frame up"],
            ["Dist1", "distribution", "routes to Core2"],
            ["Core2", "core", "routes to Dist4"],
            ["Dist4", "distribution", "routes to PC-C subnet"],
            ["Acc4", "access", "switches to PC-C"],
          ],
          hl: [1, 2],
        },
      ],
    },
    {
      title: { en: "Small site? Collapse the core", hi: "Chhoti site? Core ko collapse karo" },
      text: {
        en: "Imagine building A on its own. It needs no separate core: Dist1 and Dist2 would also do the core's job and connect straight to the WAN and internet routers. That is a two-tier, or collapsed-core, design. Add buildings and a core pays off again.",
        hi: "Socho building A akeli hai. Tab alag core ki zaroorat nahi: Dist1 aur Dist2 hi core ka kaam bhi karenge aur seedha WAN aur internet routers se judenge. Yahi two-tier, yaani collapsed-core design hai. Buildings badhti hain toh core phir se faydemand ho jaata hai.",
      },
      reset: true,
      focus: ["dist1", "dist2", "acc1", "acc2", "pca", "pcb"],
      links: [
        { id: "l-e-inet", state: "dim" },
        { id: "l-e-c1", state: "dim" },
        { id: "l-e-c2", state: "dim" },
        { id: "l-c1-c2", state: "dim" },
        { id: "l-d1-c1", state: "dim" },
        { id: "l-d1-c2", state: "dim" },
        { id: "l-d2-c1", state: "dim" },
        { id: "l-d2-c2", state: "dim" },
        { id: "l-d3-c1", state: "dim" },
        { id: "l-d3-c2", state: "dim" },
        { id: "l-d4-c1", state: "dim" },
        { id: "l-d4-c2", state: "dim" },
        { id: "l-d3-d4", state: "dim" },
        { id: "l-a3-d3", state: "dim" },
        { id: "l-a3-d4", state: "dim" },
        { id: "l-a4-d3", state: "dim" },
        { id: "l-a4-d4", state: "dim" },
        { id: "l-pcc", state: "dim" },
      ],
    },
    {
      title: { en: "Data center? Spine-leaf", hi: "Data center? Spine-leaf" },
      text: {
        en: "Now picture the same boxes as a data center fabric: Core1 and Core2 become spines, Dist1-Dist4 become leaves, and servers plug into the leaves. Each leaf keeps one link to every spine and nothing else; the spine-spine and leaf-leaf links are gone. Any leaf now reaches any other in exactly three switches, leaf → spine → leaf, and flows are shared across both spines.",
        hi: "Ab yahi boxes data center fabric ki tarah socho: Core1 aur Core2 spines ban gaye, Dist1-Dist4 leaves, aur servers leaves mein lagte hain. Har leaf ka har spine tak ek link hai aur kuch nahi; spine-spine aur leaf-leaf links hata diye. Ab koi bhi leaf kisi bhi doosre leaf tak theek teen switches mein pahunchta hai, leaf → spine → leaf, aur flows dono spines par baant diye jaate hain.",
      },
      reset: true,
      focus: ["core1", "core2", "dist1", "dist2", "dist3", "dist4"],
      badges: [
        { node: "core1", text: "Spine1", tone: "purple" },
        { node: "core2", text: "Spine2", tone: "purple" },
        { node: "dist1", text: "Leaf1", tone: "teal" },
        { node: "dist2", text: "Leaf2", tone: "teal" },
        { node: "dist3", text: "Leaf3", tone: "teal" },
        { node: "dist4", text: "Leaf4", tone: "teal" },
      ],
      links: [
        { id: "l-e-inet", state: "dim" },
        { id: "l-e-c1", state: "dim" },
        { id: "l-e-c2", state: "dim" },
        { id: "l-c1-c2", state: "dim" },
        { id: "l-d1-d2", state: "dim" },
        { id: "l-d3-d4", state: "dim" },
        { id: "l-a1-d1", state: "dim" },
        { id: "l-a1-d2", state: "dim" },
        { id: "l-a2-d1", state: "dim" },
        { id: "l-a2-d2", state: "dim" },
        { id: "l-a3-d3", state: "dim" },
        { id: "l-a3-d4", state: "dim" },
        { id: "l-a4-d3", state: "dim" },
        { id: "l-a4-d4", state: "dim" },
        { id: "l-pca", state: "dim" },
        { id: "l-pcb", state: "dim" },
        { id: "l-pcc", state: "dim" },
      ],
      packets: [
        { path: ["dist1", "core1", "dist4"], label: "Leaf1 → Leaf4", tone: "blue" },
        { path: ["dist2", "core2", "dist3"], label: "Leaf2 → Leaf3", tone: "blue" },
        { path: ["dist1", "core2", "dist2"], label: "Leaf1 → Leaf2", tone: "blue", delay: 2 },
      ],
      tables: [
        {
          node: "core1",
          title: "Leaf-to-leaf paths",
          columns: ["From", "To", "Switches crossed"],
          rows: [
            ["Leaf1", "Leaf4", "3 (via Spine1)"],
            ["Leaf2", "Leaf3", "3 (via Spine2)"],
            ["Leaf1", "Leaf2", "3 (via Spine2)"],
          ],
        },
      ],
    },
  ],
};

export default scene;
