import type { Lesson } from "../types.ts";

// Branch addressing used everywhere in this lesson and its scene:
// VLAN 10 USERS 10.1.10.0/24, VLAN 20 VOICE 10.1.20.0/24, VLAN 99 MGMT 10.1.99.0/24 (gateways .1 on DSW1), native VLAN 999 (unused)
// ASW1 10.1.99.11, ASW2 10.1.99.12, SRV1 10.1.99.50 (syslog), DSW1 Gi1/0/24 10.0.0.2/30, R1 Gi0/1 10.0.0.1/30
// R1 Gi0/0 203.0.113.2/30, ISP 203.0.113.1, WEB 198.51.100.10. PC1 gets 10.1.10.11 by DHCP.

const lesson: Lesson = {
  slug: "mega-lab",
  intro: {
    en: "Each earlier lesson configured one feature on a small topology. A real branch needs all of them at once, in an order where each step depends on the one before: no trunk, no DHCP; no route back, no DHCP either; no NAT, no internet. This capstone builds a complete branch from empty devices, then proves every feature with a show command. If you can build and verify this without notes, you can handle the configuration and simulation questions on the CCNA.",
    hi: "Pichle har lesson ne chhote topology par ek feature configure kiya. Asli branch ko sab ek saath chahiye, aur aise order mein jahan har step pichle par depend karta hai: trunk nahi toh DHCP nahi; route back nahi toh bhi DHCP nahi; NAT nahi toh internet nahi. Is capstone mein khaali devices se poora branch banaoge, phir har feature ko show command se prove karoge. Agar yeh bina notes ke bana aur verify kar liya, toh CCNA ke configuration aur simulation questions tum handle kar loge.",
  },
  outcomes: [
    { en: "Plan VLANs, subnets and device addresses for a branch before typing any command", hi: "Koi command type karne se pehle branch ke VLANs, subnets aur device addresses plan karna" },
    { en: "Build the switching layer: VLANs, access and voice ports, trunks with a native VLAN, and STP with PortFast and BPDU Guard", hi: "Switching layer banana: VLANs, access aur voice ports, native VLAN ke saath trunks, aur PortFast aur BPDU Guard ke saath STP" },
    { en: "Route between VLANs with SVIs and connect the branch with OSPF and a default route", hi: "SVIs se VLANs ke beech routing karna aur OSPF aur default route se branch ko connect karna" },
    { en: "Add DHCP with relay, PAT to the internet, SSH limited by an ACL, NTP and syslog", hi: "Relay ke saath DHCP, internet ke liye PAT, ACL se limited SSH, NTP aur syslog add karna" },
    { en: "Verify every feature with the right show command and prove the build with an end-to-end test", hi: "Har feature ko sahi show command se verify karna aur end-to-end test se poora build prove karna" },
  ],
  sections: [
    {
      id: "the-brief",
      heading: { en: "The brief and the plan", hi: "Brief aur plan" },
      blocks: [
        {
          type: "p",
          text: {
            en: "The branch has users with PCs and IP phones, one management server, two access switches (ASW1, ASW2), a multilayer distribution switch (DSW1) and an edge router (R1) connected to an ISP. DSW1 routes between the VLANs with SVIs; R1 connects the branch to the internet. (With no multilayer switch, router-on-a-stick on R1, one subinterface per VLAN, does the same routing job.) Write the plan down first. Every later command comes from these two tables.",
            hi: "Branch mein users hain PCs aur IP phones ke saath, ek management server, do access switches (ASW1, ASW2), ek multilayer distribution switch (DSW1) aur ISP se juda edge router (R1). DSW1 SVIs se VLANs ke beech routing karta hai; R1 branch ko internet se jodta hai. (Multilayer switch nahi hai toh R1 par router-on-a-stick, har VLAN ka ek subinterface, yahi routing ka kaam kar deta hai.) Pehle plan likh lo. Aage ka har command inhi do tables se aayega.",
          },
        },
        {
          type: "table",
          caption: { en: "VLAN plan", hi: "VLAN plan" },
          columns: ["VLAN", { en: "Name", hi: "Naam" }, "Subnet", { en: "Gateway (DSW1 SVI)", hi: "Gateway (DSW1 SVI)" }, { en: "Used for", hi: "Kis liye" }],
          rows: [
            ["10", "USERS", "10.1.10.0/24", "10.1.10.1", { en: "PCs, addresses by DHCP from .11", hi: "PCs, DHCP se .11 se addresses" }],
            ["20", "VOICE", "10.1.20.0/24", "10.1.20.1", { en: "IP phones, DHCP from .11", hi: "IP phones, DHCP se .11 se" }],
            ["99", "MGMT", "10.1.99.0/24", "10.1.99.1", { en: "Switch management IPs and SRV1", hi: "Switch management IPs aur SRV1" }],
            ["999", "NATIVE-UNUSED", "-", "-", { en: "Native VLAN on trunks; no ports, no hosts", hi: "Trunks ka native VLAN; na ports, na hosts" }],
          ],
        },
        {
          type: "table",
          caption: { en: "Links and addresses", hi: "Links aur addresses" },
          columns: [{ en: "Device", hi: "Device" }, "Interface", { en: "Connects to", hi: "Kisse juda" }, { en: "Address", hi: "Address" }],
          rows: [
            ["ASW1", "Gi0/1 (trunk) / Vlan99", "DSW1 Gi1/0/1", "10.1.99.11/24"],
            ["ASW2", "Gi0/1 (trunk) / Vlan99", "DSW1 Gi1/0/2", "10.1.99.12/24"],
            ["ASW1", "Fa0/1 (VLAN 10)", "PC1", { en: "DHCP (gets 10.1.10.11)", hi: "DHCP (10.1.10.11 milta hai)" }],
            ["ASW2", "Fa0/1 (voice VLAN 20)", "PH1", { en: "DHCP (gets 10.1.20.11)", hi: "DHCP (10.1.20.11 milta hai)" }],
            ["DSW1", "Gi1/0/24 (routed)", "R1 Gi0/1", "10.0.0.2/30"],
            ["DSW1", "Gi1/0/10 (VLAN 99)", "SRV1", "SRV1 = 10.1.99.50/24"],
            ["R1", "Gi0/1", "DSW1 Gi1/0/24", "10.0.0.1/30"],
            ["R1", "Gi0/0", "ISP", "203.0.113.2/30 (ISP is .1)"],
          ],
        },
        {
          type: "callout",
          tone: "tip",
          title: { en: "Packet Tracer models", hi: "Packet Tracer models" },
          text: {
            en: "Use 2960 switches for ASW1 and ASW2 (Fa0/1-24, Gi0/1-2), a 3650 for DSW1 (Gi1/0/x; add a power supply before it boots) and a 2911 router for R1 and ISP. On the ISP router put 198.51.100.1/24 on a second interface for the WEB server, and `ntp master 2` so R1 has a time source. If your Packet Tracer version rejects `ntp master`, turn on the NTP service of the WEB server and point R1 at 198.51.100.10 instead.",
            hi: "ASW1 aur ASW2 ke liye 2960 switches (Fa0/1-24, Gi0/1-2), DSW1 ke liye 3650 (Gi1/0/x; boot se pehle power supply lagao) aur R1 aur ISP ke liye 2911 router lo. ISP router ke doosre interface par WEB server ke liye 198.51.100.1/24 daalo, aur `ntp master 2` taaki R1 ko time source mile. Agar tumhara Packet Tracer version `ntp master` accept na kare, toh WEB server ki NTP service on karo aur R1 ko 198.51.100.10 par point karo.",
          },
        },
      ],
    },
    {
      id: "build-order",
      heading: { en: "Build order: why this sequence", hi: "Build order: yeh sequence kyun" },
      blocks: [
        {
          type: "p",
          text: {
            en: "Build bottom-up, the same way traffic depends on the network. A PC's first packet is a DHCP Discover; it needs an access port in the right VLAN, a trunk to carry it, an SVI with a helper address to relay it, and a route from R1 back to that SVI for the reply. Configure in that order and you can test each layer before adding the next.",
            hi: "Bottom-up banao, usi tarah jaise traffic network par depend karta hai. PC ka pehla packet DHCP Discover hota hai; use sahi VLAN ka access port chahiye, use le jaane ke liye trunk, relay karne ke liye helper address wala SVI, aur reply ke liye R1 se us SVI tak wapas route. Isi order mein configure karo, toh agla layer jodne se pehle har layer test kar sakte ho.",
          },
        },
        {
          type: "steps",
          items: [
            { en: "**VLANs and access ports** on every switch, with the voice VLAN on user ports. Test: `show vlan brief`.", hi: "Har switch par **VLANs aur access ports**, user ports par voice VLAN ke saath. Test: `show vlan brief`." },
            { en: "**Trunks** with native VLAN 999 and an allowed list. Test: `show interfaces trunk` on both ends.", hi: "Native VLAN 999 aur allowed list ke saath **trunks**. Test: dono ends par `show interfaces trunk`." },
            { en: "**STP**: Rapid PVST+, DSW1 as root, PortFast and BPDU Guard on edge ports. Test: `show spanning-tree vlan 10`.", hi: "**STP**: Rapid PVST+, DSW1 root, edge ports par PortFast aur BPDU Guard. Test: `show spanning-tree vlan 10`." },
            { en: "**SVIs and the routed uplink** on DSW1, with `ip routing`. Test: ping 10.0.0.1 from DSW1.", hi: "DSW1 par `ip routing` ke saath **SVIs aur routed uplink**. Test: DSW1 se 10.0.0.1 ping karo." },
            { en: "**OSPF** between DSW1 and R1, and a **default route** on R1 to the ISP, advertised into OSPF. Test: `show ip ospf neighbor`, `show ip route`.", hi: "DSW1 aur R1 ke beech **OSPF**, aur R1 par ISP ki taraf **default route**, OSPF mein advertise kiya hua. Test: `show ip ospf neighbor`, `show ip route`." },
            { en: "**DHCP pools** on R1 and **relay** on the SVIs. Test: the PC gets 10.1.10.11.", hi: "R1 par **DHCP pools** aur SVIs par **relay**. Test: PC ko 10.1.10.11 milta hai." },
            { en: "**NAT/PAT** on R1. Test: ping 198.51.100.10 from PC1, then `show ip nat translations`.", hi: "R1 par **NAT/PAT**. Test: PC1 se 198.51.100.10 ping karo, phir `show ip nat translations`." },
            { en: "**SSH, management ACL, NTP and syslog** on every device. Test: SSH from SRV1 works, from PC1 is refused; `show ntp associations`; `show logging`.", hi: "Har device par **SSH, management ACL, NTP aur syslog**. Test: SRV1 se SSH chalta hai, PC1 se refuse hota hai; `show ntp associations`; `show logging`." },
          ],
        },
        {
          type: "callout",
          tone: "warn",
          title: { en: "Routing before DHCP", hi: "DHCP se pehle routing" },
          text: {
            en: "You can type the DHCP pools at any time, but they only work once R1 has a route to 10.1.10.0/24. The relayed Discover reaches R1 fine; R1's Offer goes to the relay address 10.1.10.1, and without that route it is dropped. That is why OSPF comes first here.",
            hi: "DHCP pools kabhi bhi type kar sakte ho, lekin woh tabhi kaam karenge jab R1 ke paas 10.1.10.0/24 ka route ho. Relay hua Discover R1 tak aaram se pahunchta hai; R1 ka Offer relay address 10.1.10.1 par jaata hai, aur woh route na ho toh drop ho jaata hai. Isiliye yahan OSPF pehle aata hai.",
          },
        },
      ],
    },
    {
      id: "switching-layer",
      heading: { en: "Steps 1-3: VLANs, trunks and STP", hi: "Steps 1-3: VLANs, trunks aur STP" },
      blocks: [
        {
          type: "p",
          text: {
            en: "VTP transparent mode keeps each switch's VLAN list under your control and stores VLANs in the running-config, so `copy running-config startup-config` saves them. Create the same four VLANs on all three switches. Every user port carries a PC in VLAN 10 and a phone in VLAN 20, so the whole range gets both.",
            hi: "VTP transparent mode har switch ki VLAN list tumhare control mein rakhta hai aur VLANs running-config mein store karta hai, toh `copy running-config startup-config` unhe save kar deta hai. Teeno switches par same chaar VLANs banao. Har user port par VLAN 10 mein PC aur VLAN 20 mein phone hai, isliye poori range ko dono milte hain.",
          },
        },
        {
          type: "cli",
          title: { en: "ASW1 (ASW2 is identical except its hostname and 10.1.99.12)", hi: "ASW1 (ASW2 same hai, bas hostname aur 10.1.99.12 alag)" },
          lines: [
            { prompt: "Switch(config)#", cmd: "hostname ASW1" },
            { prompt: "ASW1(config)#", cmd: "vtp mode transparent" },
            { prompt: "ASW1(config)#", cmd: "vlan 10" },
            { prompt: "ASW1(config-vlan)#", cmd: "name USERS" },
            { prompt: "ASW1(config-vlan)#", cmd: "vlan 20" },
            { prompt: "ASW1(config-vlan)#", cmd: "name VOICE" },
            { prompt: "ASW1(config-vlan)#", cmd: "vlan 99" },
            { prompt: "ASW1(config-vlan)#", cmd: "name MGMT" },
            { prompt: "ASW1(config-vlan)#", cmd: "vlan 999" },
            { prompt: "ASW1(config-vlan)#", cmd: "name NATIVE-UNUSED" },
            { prompt: "ASW1(config-vlan)#", cmd: "exit" },
            { prompt: "ASW1(config)#", cmd: "interface range fa0/1 - 24" },
            { prompt: "ASW1(config-if-range)#", cmd: "switchport mode access" },
            { prompt: "ASW1(config-if-range)#", cmd: "switchport access vlan 10" },
            { prompt: "ASW1(config-if-range)#", cmd: "switchport voice vlan 20" },
            { prompt: "ASW1(config-if-range)#", cmd: "spanning-tree portfast", comment: { en: "Edge port: goes straight to forwarding", hi: "Edge port: seedha forwarding mein" } },
            { prompt: "ASW1(config-if-range)#", cmd: "spanning-tree bpduguard enable", comment: { en: "A BPDU here err-disables the port", hi: "Yahan BPDU aaya toh port err-disabled" } },
            { prompt: "ASW1(config-if-range)#", cmd: "interface gi0/1" },
            { prompt: "ASW1(config-if)#", cmd: "switchport mode trunk" },
            { prompt: "ASW1(config-if)#", cmd: "switchport trunk native vlan 999" },
            { prompt: "ASW1(config-if)#", cmd: "switchport trunk allowed vlan 10,20,99" },
            { prompt: "ASW1(config-if)#", cmd: "switchport nonegotiate", comment: { en: "No DTP on the trunk", hi: "Trunk par DTP band" } },
            { prompt: "ASW1(config-if)#", cmd: "exit" },
            { prompt: "ASW1(config)#", cmd: "spanning-tree mode rapid-pvst" },
            { prompt: "ASW1(config)#", cmd: "interface vlan 99" },
            { prompt: "ASW1(config-if)#", cmd: "ip address 10.1.99.11 255.255.255.0" },
            { prompt: "ASW1(config-if)#", cmd: "no shutdown" },
            { prompt: "ASW1(config-if)#", cmd: "exit" },
            { prompt: "ASW1(config)#", cmd: "ip default-gateway 10.1.99.1", comment: { en: "A Layer 2 switch needs this to answer other subnets", hi: "Layer 2 switch ko doosre subnets ko jawab dene ke liye yeh chahiye" } },
          ],
        },
        {
          type: "cli",
          title: { en: "DSW1: VLANs, trunks, the server port and STP root", hi: "DSW1: VLANs, trunks, server port aur STP root" },
          lines: [
            { prompt: "Switch(config)#", cmd: "hostname DSW1" },
            { prompt: "DSW1(config)#", cmd: "vtp mode transparent" },
            { comment: { en: "Create VLANs 10, 20, 99 and 999 with the same names as on ASW1", hi: "ASW1 jaise hi naamon ke saath VLANs 10, 20, 99 aur 999 banao" } },
            { prompt: "DSW1(config)#", cmd: "interface range gi1/0/1 - 2" },
            { prompt: "DSW1(config-if-range)#", cmd: "switchport trunk encapsulation dot1q", comment: { en: "Needed on switches that also support ISL; skip it if the switch rejects it (dot1q only)", hi: "ISL bhi support karne wale switches par zaroori; switch reject kare (sirf dot1q) toh skip karo" } },
            { prompt: "DSW1(config-if-range)#", cmd: "switchport mode trunk" },
            { prompt: "DSW1(config-if-range)#", cmd: "switchport trunk native vlan 999" },
            { prompt: "DSW1(config-if-range)#", cmd: "switchport trunk allowed vlan 10,20,99" },
            { prompt: "DSW1(config-if-range)#", cmd: "switchport nonegotiate" },
            { prompt: "DSW1(config-if-range)#", cmd: "interface gi1/0/10" },
            { prompt: "DSW1(config-if)#", cmd: "switchport mode access" },
            { prompt: "DSW1(config-if)#", cmd: "switchport access vlan 99" },
            { prompt: "DSW1(config-if)#", cmd: "spanning-tree portfast" },
            { prompt: "DSW1(config-if)#", cmd: "spanning-tree bpduguard enable" },
            { prompt: "DSW1(config-if)#", cmd: "exit" },
            { prompt: "DSW1(config)#", cmd: "spanning-tree mode rapid-pvst" },
            { prompt: "DSW1(config)#", cmd: "spanning-tree vlan 10,20,99 root primary", comment: { en: "Sets priority 24576 (or lower if needed) so DSW1 wins", hi: "Priority 24576 (zaroorat ho toh aur kam) set karta hai taaki DSW1 jeete" } },
          ],
        },
        {
          type: "callout",
          tone: "warn",
          title: { en: "Native VLAN must match", hi: "Native VLAN match hona chahiye" },
          text: {
            en: "Set native VLAN 999 on **both** ends of every trunk. If one end still uses VLAN 1, CDP logs a native VLAN mismatch and untagged frames leak between VLAN 1 and VLAN 999.",
            hi: "Har trunk ke **dono** ends par native VLAN 999 set karo. Ek end abhi bhi VLAN 1 par raha toh CDP native VLAN mismatch log karta hai aur untagged frames VLAN 1 aur VLAN 999 ke beech leak hote hain.",
          },
        },
      ],
    },
    {
      id: "routing-layer",
      heading: { en: "Steps 4-6: SVIs, OSPF, default route and DHCP", hi: "Steps 4-6: SVIs, OSPF, default route aur DHCP" },
      blocks: [
        {
          type: "p",
          text: {
            en: "DSW1 becomes every VLAN's default gateway. The uplink to R1 is a **routed port** (`no switchport`), a /30 with no VLAN at all. OSPF runs only on that link: `passive-interface default` stops Hellos on the SVIs, where no router listens, while still advertising their subnets. Setting the /30 to point-to-point skips the DR/BDR election on a link with only two routers.",
            hi: "DSW1 har VLAN ka default gateway banta hai. R1 ki taraf uplink ek **routed port** hai (`no switchport`), ek /30 jisme koi VLAN nahi. OSPF sirf us link par chalta hai: `passive-interface default` SVIs par Hellos band karta hai, jahan koi router sun hi nahi raha, lekin unke subnets advertise karta rehta hai. /30 ko point-to-point set karne se do hi routers wale link par DR/BDR election skip hota hai.",
          },
        },
        {
          type: "cli",
          title: { en: "DSW1: SVIs with DHCP relay, routed uplink, OSPF", hi: "DSW1: DHCP relay wale SVIs, routed uplink, OSPF" },
          lines: [
            { prompt: "DSW1(config)#", cmd: "ip routing", comment: { en: "Without this the SVIs exist but nothing is routed", hi: "Iske bina SVIs hain lekin routing nahi hoti" } },
            { prompt: "DSW1(config)#", cmd: "interface vlan 10" },
            { prompt: "DSW1(config-if)#", cmd: "ip address 10.1.10.1 255.255.255.0" },
            { prompt: "DSW1(config-if)#", cmd: "ip helper-address 10.0.0.1", comment: { en: "Relay DHCP broadcasts to R1 as unicast", hi: "DHCP broadcasts ko unicast bana kar R1 ko relay karo" } },
            { prompt: "DSW1(config-if)#", cmd: "no shutdown" },
            { prompt: "DSW1(config-if)#", cmd: "interface vlan 20" },
            { prompt: "DSW1(config-if)#", cmd: "ip address 10.1.20.1 255.255.255.0" },
            { prompt: "DSW1(config-if)#", cmd: "ip helper-address 10.0.0.1" },
            { prompt: "DSW1(config-if)#", cmd: "no shutdown" },
            { prompt: "DSW1(config-if)#", cmd: "interface vlan 99" },
            { prompt: "DSW1(config-if)#", cmd: "ip address 10.1.99.1 255.255.255.0" },
            { prompt: "DSW1(config-if)#", cmd: "no shutdown" },
            { prompt: "DSW1(config-if)#", cmd: "interface gi1/0/24" },
            { prompt: "DSW1(config-if)#", cmd: "no switchport" },
            { prompt: "DSW1(config-if)#", cmd: "ip address 10.0.0.2 255.255.255.252" },
            { prompt: "DSW1(config-if)#", cmd: "ip ospf network point-to-point" },
            { prompt: "DSW1(config-if)#", cmd: "exit" },
            { prompt: "DSW1(config)#", cmd: "router ospf 1" },
            { prompt: "DSW1(config-router)#", cmd: "router-id 2.2.2.2" },
            { prompt: "DSW1(config-router)#", cmd: "passive-interface default" },
            { prompt: "DSW1(config-router)#", cmd: "no passive-interface gi1/0/24" },
            { prompt: "DSW1(config-router)#", cmd: "network 10.1.0.0 0.0.255.255 area 0", comment: { en: "Matches all three SVIs", hi: "Teeno SVIs match karta hai" } },
            { prompt: "DSW1(config-router)#", cmd: "network 10.0.0.0 0.0.0.3 area 0" },
          ],
        },
        {
          type: "cli",
          title: { en: "R1: interfaces, default route, OSPF, DHCP pools", hi: "R1: interfaces, default route, OSPF aur DHCP pools ka config" },
          lines: [
            { prompt: "R1(config)#", cmd: "interface gi0/1" },
            { prompt: "R1(config-if)#", cmd: "ip address 10.0.0.1 255.255.255.252" },
            { prompt: "R1(config-if)#", cmd: "ip ospf network point-to-point" },
            { prompt: "R1(config-if)#", cmd: "no shutdown" },
            { prompt: "R1(config-if)#", cmd: "interface gi0/0" },
            { prompt: "R1(config-if)#", cmd: "ip address 203.0.113.2 255.255.255.252" },
            { prompt: "R1(config-if)#", cmd: "no shutdown" },
            { prompt: "R1(config-if)#", cmd: "exit" },
            { prompt: "R1(config)#", cmd: "ip route 0.0.0.0 0.0.0.0 203.0.113.1" },
            { prompt: "R1(config)#", cmd: "router ospf 1" },
            { prompt: "R1(config-router)#", cmd: "router-id 1.1.1.1" },
            { prompt: "R1(config-router)#", cmd: "network 10.0.0.0 0.0.0.3 area 0" },
            { prompt: "R1(config-router)#", cmd: "default-information originate", comment: { en: "Advertise R1's default route to DSW1", hi: "R1 ka default route DSW1 ko advertise karo" } },
            { prompt: "R1(config-router)#", cmd: "exit" },
            { prompt: "R1(config)#", cmd: "ip dhcp excluded-address 10.1.10.1 10.1.10.10" },
            { prompt: "R1(config)#", cmd: "ip dhcp excluded-address 10.1.20.1 10.1.20.10" },
            { prompt: "R1(config)#", cmd: "ip dhcp pool USERS" },
            { prompt: "R1(dhcp-config)#", cmd: "network 10.1.10.0 255.255.255.0" },
            { prompt: "R1(dhcp-config)#", cmd: "default-router 10.1.10.1" },
            { prompt: "R1(dhcp-config)#", cmd: "dns-server 8.8.8.8" },
            { prompt: "R1(dhcp-config)#", cmd: "ip dhcp pool VOICE" },
            { prompt: "R1(dhcp-config)#", cmd: "network 10.1.20.0 255.255.255.0" },
            { prompt: "R1(dhcp-config)#", cmd: "default-router 10.1.20.1" },
          ],
          note: {
            en: "R1 picks the pool from the relay's address (giaddr): a Discover relayed by 10.1.10.1 matches pool USERS, one relayed by 10.1.20.1 matches VOICE.",
            hi: "R1 pool relay ke address (giaddr) se chunta hai: 10.1.10.1 ka relay kiya Discover pool USERS se match hota hai, 10.1.20.1 ka VOICE se.",
          },
        },
        {
          type: "callout",
          tone: "tip",
          title: { en: "Connecting to HQ", hi: "HQ se connect karna" },
          text: {
            en: "If your lab has an HQ router on a WAN link from R1, give that /30 an address, add a `network` statement for it in the same OSPF process, and the branch subnets appear at HQ automatically. A static route per subnet on each side also works, but OSPF scales and reacts to failures.",
            hi: "Agar tumhare lab mein R1 se WAN link par HQ router hai, toh us /30 ko address do, usi OSPF process mein uska `network` statement add karo, aur branch ke subnets HQ par apne aap dikh jaayenge. Har side par har subnet ka static route bhi chalega, lekin OSPF scale karta hai aur failures par khud react karta hai.",
          },
        },
      ],
    },
    {
      id: "edge-and-management",
      heading: { en: "Steps 7-8: PAT, SSH with an ACL, NTP and syslog", hi: "Steps 7-8: PAT, ACL ke saath SSH, NTP aur syslog" },
      blocks: [
        {
          type: "p",
          text: {
            en: "PAT lets every 10.1.x.x host share R1's one public address, 203.0.113.2. The NAT ACL says which sources may be translated; `inside` and `outside` tell R1 which direction is which.",
            hi: "PAT se har 10.1.x.x host R1 ka ek public address, 203.0.113.2, share karta hai. NAT ACL batati hai kaunse sources translate ho sakte hain; `inside` aur `outside` R1 ko batate hain kaunsi direction kaunsi hai.",
          },
        },
        {
          type: "cli",
          title: { en: "R1: PAT", hi: "R1: PAT" },
          lines: [
            { prompt: "R1(config)#", cmd: "ip access-list standard NAT-INSIDE" },
            { prompt: "R1(config-std-nacl)#", cmd: "permit 10.1.0.0 0.0.255.255" },
            { prompt: "R1(config-std-nacl)#", cmd: "exit" },
            { prompt: "R1(config)#", cmd: "interface gi0/1" },
            { prompt: "R1(config-if)#", cmd: "ip nat inside" },
            { prompt: "R1(config-if)#", cmd: "interface gi0/0" },
            { prompt: "R1(config-if)#", cmd: "ip nat outside" },
            { prompt: "R1(config-if)#", cmd: "exit" },
            { prompt: "R1(config)#", cmd: "ip nat inside source list NAT-INSIDE interface gi0/0 overload" },
          ],
        },
        {
          type: "p",
          text: {
            en: "The management block is the same on all four devices; only the hostname-based prompt, the VTY range and the NTP server change. Only hosts in VLAN 99 (SRV1 and admin laptops plugged into VLAN 99) may open SSH sessions to any device.",
            hi: "Management block chaaron devices par same hai; sirf hostname wala prompt, VTY range aur NTP server badalte hain. Sirf VLAN 99 ke hosts (SRV1 aur VLAN 99 mein lage admin laptops) kisi bhi device par SSH session khol sakte hain.",
          },
        },
        {
          type: "cli",
          title: { en: "Every device (shown on ASW1)", hi: "Har device (ASW1 par dikhaya)" },
          lines: [
            { prompt: "ASW1(config)#", cmd: "ip domain-name branch.lab" },
            { prompt: "ASW1(config)#", cmd: "username admin privilege 15 secret Br4nch-Adm1n" },
            { prompt: "ASW1(config)#", cmd: "crypto key generate rsa modulus 2048" },
            { prompt: "ASW1(config)#", cmd: "ip ssh version 2" },
            { prompt: "ASW1(config)#", cmd: "ip access-list standard MGMT-ONLY" },
            { prompt: "ASW1(config-std-nacl)#", cmd: "permit 10.1.99.0 0.0.0.255" },
            { prompt: "ASW1(config-std-nacl)#", cmd: "exit" },
            { prompt: "ASW1(config)#", cmd: "line vty 0 15", comment: { en: "On R1 use line vty 0 4", hi: "R1 par line vty 0 4 use karo" } },
            { prompt: "ASW1(config-line)#", cmd: "access-class MGMT-ONLY in" },
            { prompt: "ASW1(config-line)#", cmd: "transport input ssh" },
            { prompt: "ASW1(config-line)#", cmd: "login local" },
            { prompt: "ASW1(config-line)#", cmd: "exit" },
            { prompt: "ASW1(config)#", cmd: "service timestamps log datetime msec" },
            { prompt: "ASW1(config)#", cmd: "logging host 10.1.99.50" },
            { prompt: "ASW1(config)#", cmd: "ntp server 10.1.99.1", comment: { en: "Access switches use DSW1; DSW1 uses 10.0.0.1; R1 uses 203.0.113.1", hi: "Access switches DSW1 use karte hain; DSW1 10.0.0.1; R1 203.0.113.1" } },
            { prompt: "ASW1(config)#", cmd: "end" },
            { prompt: "ASW1#", cmd: "copy running-config startup-config" },
          ],
          note: {
            en: "NTP forms a chain: ISP (stratum 2) → R1 (stratum 3) → DSW1 (stratum 4) → access switches (stratum 5). A Cisco device that is synchronised also answers NTP clients, so no extra server command is needed on R1 or DSW1.",
            hi: "NTP ek chain banata hai: ISP (stratum 2) → R1 (stratum 3) → DSW1 (stratum 4) → access switches (stratum 5). Sync hua Cisco device NTP clients ko jawab bhi deta hai, toh R1 ya DSW1 par alag server command ki zaroorat nahi.",
          },
        },
      ],
    },
    {
      id: "verification",
      heading: { en: "The verification checklist", hi: "Verification checklist" },
      blocks: [
        {
          type: "p",
          text: {
            en: "A build is not finished when the last command is typed. It is finished when every line below shows what it should. Work through it top to bottom. Each check depends on the ones above it, so when a line fails, fix that one before you look further down the list.",
            hi: "Aakhri command type karte hi build khatam nahi hota. Tab khatam hota hai jab neeche ki har line wahi dikhaye jo dikhana chahiye. Upar se neeche chalo. Har check apne upar wale checks par depend karta hai, isliye jo line fail ho, list mein aage dekhne se pehle usi ko theek karo.",
          },
        },
        {
          type: "table",
          columns: [{ en: "Check", hi: "Check" }, { en: "Command (where)", hi: "Command (kahan)" }, { en: "What good looks like", hi: "Sahi output kaisa dikhta hai" }],
          rows: [
            [{ en: "VLANs", hi: "VLANs" }, "show vlan brief (each switch)", { en: "10 USERS, 20 VOICE, 99 MGMT, 999 NATIVE-UNUSED active; user ports under VLAN 10", hi: "10 USERS, 20 VOICE, 99 MGMT, 999 NATIVE-UNUSED active; user ports VLAN 10 ke neeche" }],
            [{ en: "Voice VLAN", hi: "Voice VLAN" }, "show interfaces fa0/1 switchport (ASW1)", { en: "Access Mode VLAN: 10 (USERS), Voice VLAN: 20 (VOICE)", hi: "Output mein Access Mode VLAN: 10 (USERS) aur Voice VLAN: 20 (VOICE)" }],
            [{ en: "Trunks", hi: "Trunks" }, "show interfaces trunk (DSW1, ASWs)", { en: "Status trunking, native 999, allowed 10,20,99", hi: "Status trunking, native 999, allowed 10,20,99" }],
            [{ en: "STP root and edge ports", hi: "STP root aur edge ports" }, "show spanning-tree vlan 10 (DSW1); show spanning-tree interface fa0/1 detail (ASW1)", { en: "\"This bridge is the root\" on DSW1; port in portfast mode with BPDU guard enabled", hi: "DSW1 par \"This bridge is the root\"; port portfast mode mein, BPDU guard enabled" }],
            [{ en: "SVIs and uplink", hi: "SVIs aur uplink" }, "show ip interface brief (DSW1)", { en: "Vlan10, Vlan20, Vlan99 and Gi1/0/24 up/up with the planned IPs", hi: "Vlan10, Vlan20, Vlan99 aur Gi1/0/24 planned IPs ke saath up/up" }],
            [{ en: "OSPF", hi: "OSPF" }, "show ip ospf neighbor (R1)", { en: "2.2.2.2 in FULL state on Gi0/1", hi: "Gi0/1 par 2.2.2.2 FULL state mein" }],
            [{ en: "Routes", hi: "Routes" }, "show ip route (R1 and DSW1)", { en: "R1: O routes for 10.1.10/20/99.0/24 and S* default. DSW1: O*E2 0.0.0.0/0 via 10.0.0.1", hi: "R1: 10.1.10/20/99.0/24 ke O routes aur S* default. DSW1: 10.0.0.1 ke through O*E2 0.0.0.0/0" }],
            [{ en: "DHCP", hi: "DHCP" }, "show ip dhcp binding (R1); ipconfig /all (PC1)", { en: "Lease for 10.1.10.11; PC gateway 10.1.10.1, DNS 8.8.8.8", hi: "10.1.10.11 ki lease; PC ka gateway 10.1.10.1, DNS 8.8.8.8" }],
            [{ en: "NAT/PAT", hi: "NAT/PAT" }, "show ip nat translations (R1)", { en: "Inside local 10.1.10.11 mapped to inside global 203.0.113.2", hi: "Inside local 10.1.10.11, inside global 203.0.113.2 par map" }],
            [{ en: "Management ACL and SSH", hi: "Management ACL aur SSH" }, "show access-lists MGMT-ONLY; ssh -l admin 10.1.99.11 (from SRV1 and PC1)", { en: "SRV1 logs in and the match counter rises; PC1 is refused", hi: "SRV1 login kar leta hai aur match counter badhta hai; PC1 refuse hota hai" }],
            [{ en: "NTP", hi: "NTP" }, "show ntp associations; show ntp status", { en: "A * next to the server; \"Clock is synchronized\"", hi: "Server ke aage *; \"Clock is synchronized\"" }],
            [{ en: "Syslog", hi: "Syslog" }, "show logging (any device)", { en: "Logging to 10.1.99.50; messages carry date and msec timestamps", hi: "10.1.99.50 par logging; messages mein date aur msec timestamps" }],
          ],
        },
        {
          type: "cli",
          title: { en: "Three outputs worth knowing by sight", hi: "Teen outputs jo dekhte hi pehchaan lene chahiye" },
          lines: [
            { prompt: "DSW1#", cmd: "show interfaces trunk" },
            { out: "Port        Mode             Encapsulation  Status        Native vlan" },
            { out: "Gi1/0/1     on               802.1q         trunking      999" },
            { out: "Gi1/0/2     on               802.1q         trunking      999", comment: { en: "Mode on = switchport mode trunk", hi: "Mode on = switchport mode trunk" } },
            { out: "Port        Vlans allowed on trunk" },
            { out: "Gi1/0/1     10,20,99" },
            { out: "Gi1/0/2     10,20,99" },
            { prompt: "R1#", cmd: "show ip ospf neighbor" },
            { out: "Neighbor ID     Pri   State           Dead Time   Address         Interface" },
            { out: "2.2.2.2           0   FULL/  -        00:00:36    10.0.0.2        GigabitEthernet0/1", comment: { en: "Point-to-point: FULL with no DR/BDR", hi: "Point-to-point: FULL, koi DR/BDR nahi" } },
            { prompt: "R1#", cmd: "show ip nat translations" },
            { out: "Pro Inside global         Inside local          Outside local         Outside global" },
            { out: "icmp 203.0.113.2:1        10.1.10.11:1          198.51.100.10:1       198.51.100.10:1" },
            { out: "tcp 203.0.113.2:49731     10.1.10.11:49731      198.51.100.10:80      198.51.100.10:80" },
          ],
        },
        {
          type: "callout",
          tone: "exam",
          title: { en: "The final test", hi: "Aakhri test" },
          text: {
            en: "From PC1: `ipconfig` shows 10.1.10.11, `ping 10.1.99.50` succeeds (inter-VLAN routing on DSW1), `ping 198.51.100.10` succeeds (OSPF default + PAT), and the browser opens http://198.51.100.10. Then save every device with `copy running-config startup-config`.",
            hi: "PC1 se: `ipconfig` 10.1.10.11 dikhata hai, `ping 10.1.99.50` chalta hai (DSW1 par inter-VLAN routing), `ping 198.51.100.10` chalta hai (OSPF default + PAT), aur browser http://198.51.100.10 khol leta hai. Phir har device ko `copy running-config startup-config` se save karo.",
          },
        },
      ],
    },
  ],
  terms: [
    { term: "Build order", def: { en: "Configuring features in the order traffic depends on them, so each layer can be tested before the next.", hi: "Features ko usi order mein configure karna jisme traffic un par depend karta hai, taaki har layer agle se pehle test ho sake." } },
    { term: "Voice VLAN", def: { en: "A second VLAN on an access port, carried tagged for the IP phone while the PC behind it stays untagged in the access VLAN.", hi: "Access port par doosra VLAN, jo IP phone ke liye tagged jaata hai jabki uske peeche ka PC access VLAN mein untagged rehta hai." } },
    { term: "Routed port", def: { en: "A multilayer switch port turned into a router interface with `no switchport`, so it takes an IP address directly.", hi: "Multilayer switch ka port jo `no switchport` se router interface ban jaata hai, aur seedha IP address leta hai." } },
    { term: "DHCP relay (ip helper-address)", def: { en: "An SVI or router interface that turns a client's DHCP broadcast into a unicast to a DHCP server in another subnet.", hi: "SVI ya router interface jo client ke DHCP broadcast ko doosre subnet ke DHCP server ke liye unicast bana deta hai." } },
    { term: "default-information originate", def: { en: "OSPF command that advertises the router's own default route to its neighbours as an O*E2 route.", hi: "OSPF command jo router ka apna default route neighbours ko O*E2 route ke roop mein advertise karta hai." } },
    { term: "PAT (NAT overload)", def: { en: "Many inside hosts share one public address, told apart by source port.", hi: "Bahut se inside hosts ek public address share karte hain, aur source port se alag pehchaane jaate hain." } },
    { term: "access-class", def: { en: "Applies an ACL to VTY lines, limiting which sources can open Telnet or SSH sessions to the device.", hi: "VTY lines par ACL lagata hai, taaki sirf kuch sources hi device par Telnet ya SSH session khol sakein." } },
  ],
  commands: [
    { cmd: "vtp mode transparent", mode: "Global config", does: { en: "Stop VTP from changing this switch's VLANs and keep VLANs in the running-config", hi: "VTP ko is switch ke VLANs badalne se roko aur VLANs running-config mein rakho" } },
    { cmd: "switchport voice vlan 20", mode: "Interface config", does: { en: "Add a voice VLAN for an IP phone on an access port", hi: "Access port par IP phone ke liye voice VLAN add karo" } },
    { cmd: "switchport trunk native vlan 999", mode: "Interface config", does: { en: "Use an unused VLAN as the trunk's untagged VLAN", hi: "Trunk ke untagged VLAN ke liye unused VLAN use karo" } },
    { cmd: "spanning-tree vlan 10,20,99 root primary", mode: "Global config", does: { en: "Make this switch the STP root for those VLANs", hi: "Is switch ko un VLANs ka STP root banao" } },
    { cmd: "spanning-tree bpduguard enable", mode: "Interface config", does: { en: "Err-disable an edge port that receives a BPDU", hi: "BPDU aane par edge port ko err-disable karo" } },
    { cmd: "ip routing", mode: "Global config (multilayer switch)", does: { en: "Turn on IPv4 routing between SVIs and routed ports", hi: "SVIs aur routed ports ke beech IPv4 routing chalu karo" } },
    { cmd: "ip helper-address 10.0.0.1", mode: "Interface config (SVI)", does: { en: "Relay DHCP requests from this VLAN to R1", hi: "Is VLAN ki DHCP requests R1 ko relay karo" } },
    { cmd: "default-information originate", mode: "Router config (OSPF)", does: { en: "Advertise the default route into OSPF", hi: "Default route ko OSPF mein advertise karo" } },
    { cmd: "ip nat inside source list NAT-INSIDE interface gi0/0 overload", mode: "Global config", does: { en: "PAT all inside sources to Gi0/0's address", hi: "Saare inside sources ko Gi0/0 ke address par PAT karo" } },
    { cmd: "access-class MGMT-ONLY in", mode: "Line config (VTY)", does: { en: "Allow SSH to the device only from VLAN 99", hi: "Device par SSH sirf VLAN 99 se allow karo" } },
    { cmd: "show interfaces trunk", mode: "Privileged EXEC", does: { en: "Trunk status, native VLAN and allowed VLANs", hi: "Trunk status, native VLAN aur allowed VLANs" } },
    { cmd: "show ip ospf neighbor", mode: "Privileged EXEC", does: { en: "OSPF neighbours and their state", hi: "OSPF neighbours aur unki state" } },
    { cmd: "show ip nat translations", mode: "Privileged EXEC", does: { en: "Current NAT/PAT translations", hi: "Abhi ke NAT/PAT translations" } },
    { cmd: "show ip dhcp binding", mode: "Privileged EXEC", does: { en: "Addresses the DHCP server has leased", hi: "DHCP server ne jo addresses lease kiye" } },
  ],
  mistakes: [
    {
      en: "Forgetting `ip routing` on DSW1. The SVIs come up and answer pings in their own VLAN, but nothing is routed between VLANs.",
      hi: "DSW1 par `ip routing` bhool jaana. SVIs up hote hain aur apne VLAN mein ping ka jawab dete hain, lekin VLANs ke beech kuch route nahi hota.",
    },
    {
      en: "Putting `ip helper-address` on R1 instead of on the SVIs. The relay goes on the interface that **receives** the client's broadcast, which is the SVI on DSW1.",
      hi: "`ip helper-address` SVIs ki jagah R1 par lagana. Relay us interface par lagta hai jo client ka broadcast **receive** karta hai, yaani DSW1 ka SVI.",
    },
    {
      en: "Setting the native VLAN on only one end of a trunk. Both ends must say 999, or CDP reports a mismatch and untagged traffic lands in the wrong VLAN.",
      hi: "Trunk ke sirf ek end par native VLAN set karna. Dono ends par 999 hona chahiye, warna CDP mismatch report karta hai aur untagged traffic galat VLAN mein pahunchta hai.",
    },
    {
      en: "Leaving out `ip default-gateway` on the access switches. You can SSH to them from VLAN 99, but not from any other subnet, and they cannot reach the syslog or NTP server if it is elsewhere.",
      hi: "Access switches par `ip default-gateway` chhod dena. VLAN 99 se unpar SSH ho jaayega, lekin kisi aur subnet se nahi, aur syslog ya NTP server kahin aur ho toh switch wahan tak nahi pahunchega.",
    },
    {
      en: "Marking the wrong interfaces `ip nat inside` / `outside`, or forgetting one. PAT needs both, facing the right way.",
      hi: "Galat interfaces ko `ip nat inside` / `outside` mark karna, ya ek bhool jaana. PAT ko dono chahiye, sahi direction mein.",
    },
    {
      en: "Not saving. A reload in Packet Tracer or on real gear loses the whole build; `copy running-config startup-config` on every device at the end.",
      hi: "Save na karna. Packet Tracer ya real gear par ek reload poora build mita deta hai; aakhir mein har device par `copy running-config startup-config`.",
    },
  ],
  recap: [
    { en: "Plan first: VLAN table and link/address table. Every command comes from them.", hi: "Pehle plan: VLAN table aur link/address table. Har command inhi se aata hai." },
    { en: "Order: VLANs and ports, trunks, STP, SVIs and uplink, OSPF and default route, DHCP and relay, PAT, then SSH, ACL, NTP and syslog.", hi: "Order: VLANs aur ports, trunks, STP, SVIs aur uplink, OSPF aur default route, DHCP aur relay, PAT, phir SSH, ACL, NTP aur syslog." },
    { en: "DHCP across subnets needs `ip helper-address` on the SVI and a route from the server back to the SVI.", hi: "Subnets ke paar DHCP ko SVI par `ip helper-address` aur server se SVI tak wapas route chahiye." },
    { en: "`default-information originate` gives the branch its O*E2 default route; PAT makes that route usable for private hosts.", hi: "`default-information originate` branch ko O*E2 default route deta hai; PAT us route ko private hosts ke liye usable banata hai." },
    { en: "Verify each layer with its show command, then finish with an end-to-end ping and web request, and save everything.", hi: "Har layer ko uske show command se verify karo, phir end-to-end ping aur web request se khatam karo, aur sab save karo." },
  ],
  quiz: [
    {
      q: {
        en: "PC1 in VLAN 10 shows a 169.254.x.x address. R1 has a correct USERS pool, OSPF is FULL and R1 has a route to 10.1.10.0/24. What is the most likely missing command?",
        hi: "VLAN 10 ka PC1 169.254.x.x address dikha raha hai. R1 par USERS pool sahi hai, OSPF FULL hai aur R1 ke paas 10.1.10.0/24 ka route hai. Sabse zyada chance kis command ke missing hone ka hai?",
      },
      options: [
        { en: "`ip dhcp excluded-address 10.1.10.1 10.1.10.10` on R1", hi: "R1 par `ip dhcp excluded-address 10.1.10.1 10.1.10.10`" },
        { en: "`default-information originate` on R1", hi: "R1 par `default-information originate`" },
        { en: "`ip nat inside` on R1 Gi0/1", hi: "R1 Gi0/1 par `ip nat inside`" },
        { en: "`ip helper-address 10.0.0.1` under `interface vlan 10` on DSW1", hi: "DSW1 par `interface vlan 10` ke neeche `ip helper-address 10.0.0.1`" },
      ],
      answer: 3,
      explain: {
        en: "A 169.254 address means no DHCP reply arrived. The Discover is a broadcast and stops at DSW1's SVI unless that SVI relays it. Excluded addresses, the default route and NAT have nothing to do with getting a lease.",
        hi: "169.254 address ka matlab koi DHCP reply nahi aaya. Discover broadcast hai aur DSW1 ke SVI par ruk jaata hai, jab tak woh SVI use relay na kare. Excluded addresses, default route aur NAT ka lease milne se koi lena-dena nahi.",
      },
      kind: "scenario",
    },
    {
      q: {
        en: "`show interfaces trunk` on ASW2 shows Native vlan 1 on Gi0/1, while DSW1 shows 999 on Gi1/0/2. What should you do?",
        hi: "ASW2 par `show interfaces trunk` Gi0/1 par Native vlan 1 dikhata hai, jabki DSW1 Gi1/0/2 par 999 dikhata hai. Kya karna chahiye?",
      },
      options: [
        { en: "Configure `switchport trunk native vlan 999` on ASW2 Gi0/1", hi: "ASW2 Gi0/1 par `switchport trunk native vlan 999` configure karo" },
        { en: "Remove VLAN 999 from DSW1", hi: "DSW1 se VLAN 999 hata do" },
        { en: "Add VLAN 1 to the allowed list on DSW1", hi: "DSW1 ki allowed list mein VLAN 1 add karo" },
        { en: "Nothing; the native VLAN only matters on one end", hi: "Kuch nahi; native VLAN sirf ek end par matter karta hai" },
      ],
      answer: 0,
      explain: {
        en: "The native VLAN must match on both ends. The plan says 999, so fix the end that is wrong. Changing DSW1 back to VLAN 1 would also remove the mismatch, but it would break the design.",
        hi: "Native VLAN dono ends par match hona chahiye. Plan 999 kehta hai, toh jo end galat hai use theek karo. DSW1 ko wapas VLAN 1 par le jaane se bhi mismatch hat jaata, lekin design toot jaata.",
      },
      kind: "cli",
    },
    {
      q: {
        en: "From SRV1 (10.1.99.50) you can SSH to ASW1, but from PC1 (10.1.10.11) the connection is refused. Why?",
        hi: "SRV1 (10.1.99.50) se ASW1 par SSH ho jaata hai, lekin PC1 (10.1.10.11) se connection refuse hota hai. Kyun?",
      },
      options: [
        { en: "ASW1 has no default gateway", hi: "ASW1 ka koi default gateway nahi hai" },
        { en: "PC1's VLAN is not allowed on the trunk", hi: "PC1 ka VLAN trunk par allowed nahi hai" },
        { en: "`access-class MGMT-ONLY in` on the VTY lines permits only 10.1.99.0/24", hi: "VTY lines par `access-class MGMT-ONLY in` sirf 10.1.99.0/24 permit karta hai" },
        { en: "SSH version 2 does not work across VLANs", hi: "SSH version 2 VLANs ke paar kaam nahi karta" },
      ],
      answer: 2,
      explain: {
        en: "This is the ACL doing its job. PC1's packets reach ASW1 (routed by DSW1, then down the trunk in VLAN 99), but the access-class rejects the source 10.1.10.11. A missing default gateway would break replies to every other subnet, but then the session would time out, not be refused.",
        hi: "Yeh ACL apna kaam kar rahi hai. PC1 ke packets ASW1 tak pahunchte hain (DSW1 route karta hai, phir VLAN 99 mein trunk se neeche), lekin access-class source 10.1.10.11 ko reject kar deta hai. Default gateway missing hota toh doosre subnets ko reply hi nahi jaata, aur session refuse hone ki jagah time out hota.",
      },
      kind: "scenario",
    },
    {
      q: { en: "Which command proves that PC1's web traffic is being translated by PAT?", hi: "Kaunsa command prove karta hai ki PC1 ka web traffic PAT se translate ho raha hai?" },
      options: [
        { en: "`show ip route` on R1", hi: "R1 par `show ip route`" },
        { en: "`show ip nat translations` on R1", hi: "R1 par `show ip nat translations`" },
        { en: "`show ip dhcp binding` on R1", hi: "R1 par `show ip dhcp binding`" },
        { en: "`show access-lists MGMT-ONLY` on R1", hi: "R1 par `show access-lists MGMT-ONLY`" },
      ],
      answer: 1,
      explain: {
        en: "The translation table lists each flow: inside local 10.1.10.11:port mapped to inside global 203.0.113.2:port. The routing table shows a path exists, not that addresses are being rewritten.",
        hi: "Translation table har flow dikhati hai: inside local 10.1.10.11:port, inside global 203.0.113.2:port par map. Routing table sirf batata hai ki raasta hai, yeh nahi ki addresses rewrite ho rahe hain.",
      },
      kind: "cli",
    },
    {
      q: {
        en: "From R1 you can ping 10.1.99.1 but not ASW1 at 10.1.99.11. From SRV1, ping 10.1.99.11 works. What is ASW1 most likely missing?",
        hi: "R1 se 10.1.99.1 ping hota hai lekin 10.1.99.11 par ASW1 nahi. SRV1 se 10.1.99.11 ping chalta hai. ASW1 mein sabse zyada chance kya missing hai?",
      },
      options: [
        { en: "`ip routing`", hi: "`ip routing`" },
        { en: "`switchport voice vlan 20`", hi: "`switchport voice vlan 20`" },
        { en: "`spanning-tree portfast`", hi: "`spanning-tree portfast`" },
        { en: "`ip default-gateway 10.1.99.1`", hi: "`ip default-gateway 10.1.99.1`" },
      ],
      answer: 3,
      explain: {
        en: "SRV1 is in the same subnet, so ASW1 replies directly. R1's ping comes from 10.0.0.1, another subnet, and a Layer 2 switch needs `ip default-gateway` to send the reply. `ip routing` is for the multilayer switch, not the access switch.",
        hi: "SRV1 same subnet mein hai, toh ASW1 seedha reply karta hai. R1 ka ping 10.0.0.1 se aata hai, jo doosra subnet hai, aur Layer 2 switch ko reply bhejne ke liye `ip default-gateway` chahiye. `ip routing` multilayer switch ke liye hai, access switch ke liye nahi.",
      },
      kind: "scenario",
    },
    {
      q: {
        en: "A user plugs a small managed switch that sends BPDUs into ASW1 Fa0/5. What happens with this lesson's config?",
        hi: "Ek user ASW1 Fa0/5 mein ek chhota managed switch laga deta hai jo BPDUs bhejta hai. Is lesson ke config ke saath kya hoga?",
      },
      options: [
        { en: "The new switch becomes the STP root for VLAN 10", hi: "Naya switch VLAN 10 ka STP root ban jaata hai" },
        { en: "Fa0/5 is err-disabled by BPDU Guard", hi: "BPDU Guard Fa0/5 ko err-disable kar deta hai" },
        { en: "Fa0/5 becomes a trunk through DTP", hi: "DTP se Fa0/5 trunk ban jaata hai" },
        { en: "PortFast keeps the port forwarding normally", hi: "PortFast port ko normally forwarding mein rakhta hai" },
      ],
      answer: 1,
      explain: {
        en: "BPDU Guard on an edge port shuts it down (err-disabled) the moment a BPDU arrives, so the rogue switch can never take part in STP or become root. The port is set to `switchport mode access`, so DTP cannot turn it into a trunk.",
        hi: "Edge port par BPDU Guard, BPDU aate hi port ko band (err-disabled) kar deta hai, toh rogue switch kabhi STP mein hissa nahi le sakta ya root nahi ban sakta. Port `switchport mode access` par set hai, isliye DTP use trunk nahi bana sakta.",
      },
      kind: "scenario",
    },
  ],
  videos: [
    {
      id: "2p7-MluKAgE",
      title: "Complete Network Configuration // CCNA Mega Lab! / OSPF, VLANs, STP, DHCP, Security, Wireless + more",
      channel: "Jeremy's IT Lab",
      lang: "en",
      note: {
        en: "A full build of a larger network with the same features, step by step in Packet Tracer. Long, but you can follow it task by task; download his lab file and try each task before watching it.",
        hi: "Isi tarah ke features ke saath ek bade network ka poora build, Packet Tracer mein step by step. Lamba hai, lekin task by task follow kar sakte ho; unki lab file download karo aur har task dekhne se pehle khud try karo.",
      },
    },
    {
      id: "u2eJdE9MxL8",
      title: "How to Design and Configure a Campus Area Network in Hindi | Networking Project in Hindi | CAN |",
      channel: "Network Nuggets",
      lang: "hi",
      note: { en: "A Hindi campus network project: design first, then VLANs, routing and services configured together.", hi: "Hindi mein campus network project: pehle design, phir VLANs, routing aur services ek saath configure." },
    },
  ],
  lab: {
    title: { en: "Build and verify the branch", hi: "Branch banao aur verify karo" },
    steps: [
      { en: "Place PC1, PH1 (an IP phone with a power adapter), SRV1, ASW1, ASW2, DSW1, R1, ISP and WEB in Packet Tracer and cable them as in the links table (R1 Gi0/0 to ISP, the ISP's second interface to WEB). Set SRV1 to 10.1.99.50/24, gateway 10.1.99.1, and turn on its Syslog service.", hi: "Packet Tracer mein PC1, PH1 (power adapter ke saath IP phone), SRV1, ASW1, ASW2, DSW1, R1, ISP aur WEB rakho aur links table ke hisaab se cable karo (R1 Gi0/0 se ISP, ISP ke doosre interface se WEB). SRV1 ko 10.1.99.50/24, gateway 10.1.99.1 do, aur uski Syslog service on karo." },
      { en: "Configure steps 1-3 and check `show vlan brief`, `show interfaces trunk` and `show spanning-tree vlan 10` before going on.", hi: "Steps 1-3 configure karo aur aage badhne se pehle `show vlan brief`, `show interfaces trunk` aur `show spanning-tree vlan 10` check karo." },
      { en: "Configure steps 4-6. Set PC1 and PH1 to DHCP and confirm they get 10.1.10.11 and 10.1.20.11.", hi: "Steps 4-6 configure karo. PC1 aur PH1 ko DHCP par set karo aur confirm karo ki unhe 10.1.10.11 aur 10.1.20.11 milte hain." },
      { en: "Configure steps 7-8. Ping 198.51.100.10 from PC1, open it in PC1's web browser, and read `show ip nat translations`.", hi: "Steps 7-8 configure karo. PC1 se 198.51.100.10 ping karo, PC1 ke web browser mein kholo, aur `show ip nat translations` padho." },
      { en: "Run the whole verification checklist and fix anything that does not match, starting from the top of the list.", hi: "Poori verification checklist chalao aur jo match na kare use theek karo, list ke upar se shuru karke." },
      { en: "Break it on purpose: remove `ip helper-address` from Vlan10, renew PC1's address, and watch what fails. Put it back and save every device.", hi: "Jaan boojh kar todo: Vlan10 se `ip helper-address` hatao, PC1 ka address renew karo, aur dekho kya fail hota hai. Wapas lagao aur har device save karo." },
    ],
  },
};

export default lesson;
