import type { CliLab } from "../lab.ts";

const lab: CliLab = {
  id: "branch-capstone",
  title: { en: "Capstone: build a complete branch office", hi: "Capstone: poora branch office build karo" },
  level: "advanced",
  kind: "challenge",
  minutes: 90,
  lessons: ["mega-lab", "vlans", "trunking", "inter-vlan-routing", "dhcp", "ospf-config", "nat", "acl-standard", "ssh"],
  scenario: {
    en: "The company is opening a new branch and you are the only network engineer on site. The racks are cabled, the devices are blank apart from their names. The HQ team has already set up their side of the WAN link (HQ is 10.0.0.1/30, OSPF area 0) and the ISP has handed over 203.0.113.2/30 with gateway 203.0.113.1. By the end of the day users must get addresses automatically, reach HQ and the internet, and only the IT VLAN may log in to the network devices. Plan your addressing from the drawing, build it, test it and save it.",
    hi: "Company ek naya branch khol rahi hai aur site par tum akele network engineer ho. Racks cabled hain, devices par naam ke alawa kuch configure nahi hai. HQ team ne WAN link ka apna side already set kar diya hai (HQ 10.0.0.1/30 hai, OSPF area 0), aur ISP ne 203.0.113.2/30 diya hai jiska gateway 203.0.113.1 hai. Din khatam hone tak users ko address apne aap milna chahiye, woh HQ aur internet tak pahunch sakein, aur network devices par login sirf IT VLAN se ho. Drawing dekh kar addressing plan karo, build karo, test karo aur save karo.",
  },
  devices: [
    { id: "srv", kind: "server", hostname: "HQ-Server", x: 80, y: 70, host: { ip: "172.16.1.10", prefix: 24, gateway: "172.16.1.1", services: ["http"] }, note: "172.16.1.10" },
    { id: "hq", kind: "router", hostname: "HQ", x: 230, y: 70, note: "10.0.0.1 (OSPF)", locked: true, config: [
      "interface g0/0", "ip address 10.0.0.1 255.255.255.252", "no shutdown",
      "interface g0/1", "ip address 172.16.1.1 255.255.255.0", "no shutdown",
      "router ospf 1", "router-id 1.1.1.1", "network 10.0.0.0 0.0.0.3 area 0", "network 172.16.1.0 0.0.0.255 area 0", "passive-interface g0/1",
    ] },
    { id: "br1", kind: "router", hostname: "BR1", x: 400, y: 70, note: "Branch router" },
    { id: "isp", kind: "router", hostname: "ISP", x: 620, y: 70, note: "203.0.113.1, Lo0 8.8.8.8", locked: true, config: [
      "interface g0/0", "ip address 203.0.113.1 255.255.255.252", "no shutdown",
      "interface lo0", "ip address 8.8.8.8 255.255.255.255",
    ] },
    { id: "sw1", kind: "switch", hostname: "SW1", x: 260, y: 210, note: "Mgmt 192.168.99.11" },
    { id: "sw2", kind: "switch", hostname: "SW2", x: 540, y: 210, note: "Mgmt 192.168.99.12" },
    { id: "user1", kind: "pc", hostname: "User-1", x: 100, y: 370, host: { dhcp: true }, note: "VLAN 10, DHCP" },
    { id: "admin", kind: "pc", hostname: "Admin-PC", x: 250, y: 370, host: { ip: "192.168.99.50", prefix: 24, gateway: "192.168.99.1" }, note: "VLAN 99, .99.50" },
    { id: "user2", kind: "pc", hostname: "User-2", x: 470, y: 370, host: { dhcp: true }, note: "VLAN 10, DHCP" },
    { id: "staff1", kind: "pc", hostname: "Staff-1", x: 640, y: 370, host: { ip: "192.168.20.11", prefix: 24, gateway: "192.168.20.1" }, note: "VLAN 20, .20.11" },
  ],
  links: [
    ["srv", "FastEthernet0", "hq", "GigabitEthernet0/1"],
    ["hq", "GigabitEthernet0/0", "br1", "GigabitEthernet0/1"],
    ["br1", "GigabitEthernet0/2", "isp", "GigabitEthernet0/0"],
    ["br1", "GigabitEthernet0/0", "sw1", "GigabitEthernet0/1"],
    ["sw1", "GigabitEthernet0/2", "sw2", "GigabitEthernet0/1"],
    ["user1", "FastEthernet0", "sw1", "FastEthernet0/1"],
    ["admin", "FastEthernet0", "sw1", "FastEthernet0/24"],
    ["user2", "FastEthernet0", "sw2", "FastEthernet0/1"],
    ["staff1", "FastEthernet0", "sw2", "FastEthernet0/2"],
  ],
  height: 460,
  tasks: [
    {
      text: {
        en: "On both switches create VLAN 10 USERS, VLAN 20 STAFF and VLAN 99 MGMT. Put every PC port in the VLAN shown in the drawing (SW1 Fa0/1 and Fa0/24, SW2 Fa0/1 and Fa0/2).",
        hi: "Dono switches par VLAN 10 USERS, VLAN 20 STAFF aur VLAN 99 MGMT banao. Har PC port ko drawing mein dikhaye gaye VLAN mein daalo (SW1 par Fa0/1 aur Fa0/24, SW2 par Fa0/1 aur Fa0/2).",
      },
      hint: {
        en: "`vlan` with `name` creates and names a VLAN. Ports to PCs are access ports: `switchport mode access` and `switchport access vlan`. Check with `show vlan brief`.",
        hi: "`vlan` aur `name` se VLAN banta hai aur naam milta hai. PC wale ports access ports hote hain: `switchport mode access` aur `switchport access vlan`. `show vlan brief` se check karo.",
      },
      check: [
        { t: "vlan", dev: "sw1", id: 10, name: "USERS" },
        { t: "vlan", dev: "sw1", id: 20, name: "STAFF" },
        { t: "vlan", dev: "sw1", id: 99, name: "MGMT" },
        { t: "vlan", dev: "sw2", id: 10, name: "USERS" },
        { t: "vlan", dev: "sw2", id: 20, name: "STAFF" },
        { t: "vlan", dev: "sw2", id: 99, name: "MGMT" },
        { t: "access", dev: "sw1", iface: "FastEthernet0/1", vlan: 10 },
        { t: "access", dev: "sw1", iface: "FastEthernet0/24", vlan: 99 },
        { t: "access", dev: "sw2", iface: "FastEthernet0/1", vlan: 10 },
        { t: "access", dev: "sw2", iface: "FastEthernet0/2", vlan: 20 },
      ],
    },
    {
      text: {
        en: "Make the SW1-BR1 link and the SW1-SW2 link static trunks that carry only VLANs 10, 20 and 99.",
        hi: "SW1-BR1 link aur SW1-SW2 link ko static trunks banao jo sirf VLAN 10, 20 aur 99 carry karein.",
      },
      hint: {
        en: "Don't rely on DTP: set the trunk mode yourself and limit the allowed VLAN list on each switch end. `show interfaces trunk` shows what is really trunking.",
        hi: "DTP par bharosa mat karo: trunk mode khud set karo aur har switch end par allowed VLAN list limit karo. Asal mein kya trunk ho raha hai, woh `show interfaces trunk` dikhata hai.",
      },
      check: [
        { t: "trunk", dev: "sw1", iface: "GigabitEthernet0/1", allowed: [10, 20, 99] },
        { t: "trunk", dev: "sw1", iface: "GigabitEthernet0/2", allowed: [10, 20, 99] },
        { t: "trunk", dev: "sw2", iface: "GigabitEthernet0/1", allowed: [10, 20, 99] },
        { t: "config", dev: "sw1", section: "interface GigabitEthernet0/1", has: "switchport mode trunk" },
        { t: "config", dev: "sw1", section: "interface GigabitEthernet0/2", has: "switchport mode trunk" },
        { t: "config", dev: "sw2", section: "interface GigabitEthernet0/1", has: "switchport mode trunk" },
      ],
    },
    {
      text: {
        en: "Route between the VLANs on BR1 with one physical link to SW1. Each VLAN's gateway is .1 in its subnet: 192.168.10.0/24, 192.168.20.0/24 and 192.168.99.0/24. Admin-PC must reach Staff-1.",
        hi: "BR1 par VLANs ke beech routing karo, SW1 tak sirf ek physical link ke saath. Har VLAN ka gateway uske subnet ka .1 hai: 192.168.10.0/24, 192.168.20.0/24 aur 192.168.99.0/24. Admin-PC ko Staff-1 tak pahunchna chahiye.",
      },
      hint: {
        en: "Router-on-a-stick: one subinterface per VLAN on Gi0/0, each with an 802.1Q tag and the gateway address. Router interfaces start shut down, so remember the parent interface.",
        hi: "Router-on-a-stick: Gi0/0 par har VLAN ke liye ek subinterface, har ek par 802.1Q tag aur gateway address. Router interfaces shutdown state mein start hote hain, isliye parent interface ko mat bhoolna.",
      },
      check: [
        { t: "ping", from: "admin", to: "192.168.20.11" },
        { t: "ping", from: "staff1", to: "192.168.99.1" },
      ],
    },
    {
      text: {
        en: "BR1 hands out addresses in VLAN 10: gateway 192.168.10.1, DNS 8.8.8.8, and 192.168.10.1 to 192.168.10.20 kept out of the pool for fixed devices. Both users must get a lease and reach Staff-1.",
        hi: "BR1 VLAN 10 mein addresses de: gateway 192.168.10.1, DNS 8.8.8.8, aur fixed devices ke liye 192.168.10.1 se 192.168.10.20 tak pool se bahar rakho. Dono users ko lease milni chahiye aur woh Staff-1 tak pahunch sakein.",
      },
      hint: {
        en: "Exclude first, then build the pool with its network, default router and DNS server. On the PCs, `ipconfig /renew` asks for a lease; `show ip dhcp binding` on BR1 lists what was given out.",
        hi: "Pehle exclude karo, phir pool banao jisme network, default router aur DNS server ho. PCs par `ipconfig /renew` lease maangta hai; BR1 par `show ip dhcp binding` dikhata hai kya diya gaya.",
      },
      check: [
        { t: "config", dev: "br1", has: "^ip dhcp excluded-address 192\\.168\\.10\\.1 192\\.168\\.10\\.20$" },
        { t: "config", dev: "br1", has: "^ dns-server 8\\.8\\.8\\.8$" },
        { t: "dhcp", host: "user1" },
        { t: "dhcp", host: "user2" },
        { t: "ping", from: "user1", to: "192.168.20.11" },
        { t: "ping", from: "user2", to: "192.168.20.11" },
      ],
    },
    {
      text: {
        en: "Bring up OSPF process 1 between BR1 and HQ in area 0 (the link is 10.0.0.0/30, BR1 is .2). HQ must learn all three branch subnets, no OSPF hellos may go out to the branch VLANs, and User-1 must reach HQ-Server.",
        hi: "BR1 aur HQ ke beech area 0 mein OSPF process 1 chalao (link 10.0.0.0/30 hai, BR1 .2 hai). HQ ko teeno branch subnets seekhne chahiye, branch VLANs ki taraf koi OSPF hello nahi jaana chahiye, aur User-1 HQ-Server tak pahunch sake.",
      },
      hint: {
        en: "Address Gi0/1 first, then advertise the WAN link and the three VLAN subnets. Make the VLAN subinterfaces passive (or make everything passive and open only the WAN link). `show ip ospf neighbor` should show HQ as FULL.",
        hi: "Pehle Gi0/1 par address do, phir WAN link aur teeno VLAN subnets advertise karo. VLAN subinterfaces ko passive banao (ya sab kuch passive karke sirf WAN link kholo). `show ip ospf neighbor` mein HQ FULL dikhna chahiye.",
      },
      check: [
        { t: "ospf", dev: "br1", neighbors: 1 },
        { t: "route", dev: "hq", prefix: "192.168.10.0/24", code: "O" },
        { t: "route", dev: "hq", prefix: "192.168.20.0/24", code: "O" },
        { t: "route", dev: "hq", prefix: "192.168.99.0/24", code: "O" },
        { t: "config", dev: "br1", section: "router ospf 1", has: "^ passive-interface (default|GigabitEthernet0/0\\.10)$" },
        { t: "ping", from: "user1", to: "172.16.1.10" },
      ],
    },
    {
      text: {
        en: "Give the user and staff VLANs internet access through the ISP: a default route to 203.0.113.1, and all of 10 and 20 sharing BR1's public address on Gi0/2 (203.0.113.2/30). Traffic to HQ must not be translated.",
        hi: "User aur staff VLANs ko ISP ke through internet do: 203.0.113.1 ki taraf default route, aur VLAN 10 aur 20 dono BR1 ka Gi0/2 wala public address (203.0.113.2/30) share karein. HQ jaane wala traffic translate nahi hona chahiye.",
      },
      hint: {
        en: "This is PAT: an ACL that matches the inside subnets, `ip nat inside` and `ip nat outside` on the right interfaces, and one `ip nat inside source list ... interface ... overload` line. `show ip nat translations` proves it.",
        hi: "Yeh PAT hai: ek ACL jo inside subnets match kare, sahi interfaces par `ip nat inside` aur `ip nat outside`, aur ek `ip nat inside source list ... interface ... overload` line. `show ip nat translations` se proof milta hai.",
      },
      check: [
        { t: "config", dev: "br1", has: "^ip nat inside source list \\S+ interface GigabitEthernet0/2 overload$" },
        { t: "ping", from: "user2", to: "8.8.8.8" },
        { t: "ping", from: "staff1", to: "8.8.8.8" },
        { t: "ping", from: "user2", to: "172.16.1.10" },
      ],
    },
    {
      text: {
        en: "Manage the switches in VLAN 99: SW1 is 192.168.99.11 and SW2 is 192.168.99.12. They must answer pings from the other VLANs too.",
        hi: "Switches ko VLAN 99 mein manage karo: SW1 192.168.99.11 hai aur SW2 192.168.99.12. Dusre VLANs se aane wale pings ka bhi jawab dena chahiye.",
      },
      hint: {
        en: "A Layer 2 switch gets its address on an SVI. Replies to other subnets need a way out: a switch doesn't route, so it needs `ip default-gateway`.",
        hi: "Layer 2 switch ko address SVI par milta hai. Dusre subnets ko reply bhejne ke liye raasta chahiye: switch route nahi karta, isliye use `ip default-gateway` chahiye.",
      },
      check: [
        { t: "ping", from: "admin", to: "192.168.99.12" },
        { t: "ping", from: "user1", to: "192.168.99.11" },
        { t: "ping", from: "user1", to: "192.168.99.12" },
      ],
    },
    {
      text: {
        en: "BR1, SW1 and SW2 accept SSH version 2 only, with a local admin account, and only from VLAN 99. Admin-PC can log in to all three; User-1 can't open SSH to any of them; Telnet works for nobody.",
        hi: "BR1, SW1 aur SW2 sirf SSH version 2 accept karein, local admin account ke saath, aur sirf VLAN 99 se. Admin-PC teeno par login kar sake; User-1 kisi par bhi SSH na khol sake; Telnet kisi ke liye kaam na kare.",
      },
      hint: {
        en: "Each device needs a domain name, a local user, RSA keys and SSH version 2. On the VTY lines use the local database and SSH transport, and filter who may connect with a standard ACL applied by `access-class ... in`.",
        hi: "Har device ko domain name, local user, RSA keys aur SSH version 2 chahiye. VTY lines par local database aur SSH transport use karo, aur kaun connect kar sakta hai yeh standard ACL se filter karo jo `access-class ... in` se lagta hai.",
      },
      check: [
        { t: "tcp", from: "admin", to: "192.168.99.1", port: 22 },
        { t: "tcp", from: "admin", to: "192.168.99.11", port: 22 },
        { t: "tcp", from: "admin", to: "192.168.99.12", port: 22 },
        { t: "tcp", from: "user1", to: "192.168.10.1", port: 22, ok: false },
        { t: "tcp", from: "user1", to: "192.168.99.11", port: 22, ok: false },
        { t: "tcp", from: "user1", to: "192.168.99.12", port: 22, ok: false },
        { t: "tcp", from: "admin", to: "192.168.99.1", port: 23, ok: false },
        { t: "tcp", from: "admin", to: "192.168.99.11", port: 23, ok: false },
        { t: "tcp", from: "admin", to: "192.168.99.12", port: 23, ok: false },
        { t: "config", dev: "br1", has: "^username \\S+ privilege 15 secret" },
        { t: "config", dev: "sw1", has: "^username \\S+ privilege 15 secret" },
        { t: "config", dev: "sw2", has: "^username \\S+ privilege 15 secret" },
        { t: "config", dev: "br1", section: "line vty 0 4", has: "login local" },
        { t: "config", dev: "sw1", section: "line vty 0 4", has: "login local" },
        { t: "config", dev: "sw2", section: "line vty 0 4", has: "login local" },
        { t: "config", dev: "br1", has: "^ip ssh version 2$" },
        { t: "config", dev: "sw1", has: "^ip ssh version 2$" },
        { t: "config", dev: "sw2", has: "^ip ssh version 2$" },
      ],
    },
    {
      text: { en: "Save the configuration on BR1, SW1 and SW2.", hi: "BR1, SW1 aur SW2 ki configuration save karo." },
      hint: {
        en: "Running config lives in RAM. Copy it to the startup config on each device after your last change.",
        hi: "Running config RAM mein rehta hai. Aakhri change ke baad har device par use startup config mein copy karo.",
      },
      check: [
        { t: "saved", dev: "br1" },
        { t: "saved", dev: "sw1" },
        { t: "saved", dev: "sw2" },
      ],
    },
  ],
  solution: {
    sw1: [
      "vlan 10", "name USERS", "vlan 20", "name STAFF", "vlan 99", "name MGMT", "exit",
      "interface f0/1", "switchport mode access", "switchport access vlan 10",
      "interface f0/24", "switchport mode access", "switchport access vlan 99",
      "interface range g0/1 - 2", "switchport mode trunk", "switchport trunk allowed vlan 10,20,99", "switchport nonegotiate",
      "interface vlan 99", "ip address 192.168.99.11 255.255.255.0", "no shutdown", "exit",
      "ip default-gateway 192.168.99.1",
      "ip domain-name branch.lab",
      "username admin privilege 15 secret Br4nch!Adm1n",
      "crypto key generate rsa modulus 2048",
      "ip ssh version 2",
      "access-list 10 permit 192.168.99.0 0.0.0.255",
      "line vty 0 15", "login local", "transport input ssh", "access-class 10 in",
      "end", "copy running-config startup-config",
    ],
    sw2: [
      "vlan 10", "name USERS", "vlan 20", "name STAFF", "vlan 99", "name MGMT", "exit",
      "interface f0/1", "switchport mode access", "switchport access vlan 10",
      "interface f0/2", "switchport mode access", "switchport access vlan 20",
      "interface g0/1", "switchport mode trunk", "switchport trunk allowed vlan 10,20,99", "switchport nonegotiate",
      "interface vlan 99", "ip address 192.168.99.12 255.255.255.0", "no shutdown", "exit",
      "ip default-gateway 192.168.99.1",
      "ip domain-name branch.lab",
      "username admin privilege 15 secret Br4nch!Adm1n",
      "crypto key generate rsa modulus 2048",
      "ip ssh version 2",
      "access-list 10 permit 192.168.99.0 0.0.0.255",
      "line vty 0 15", "login local", "transport input ssh", "access-class 10 in",
      "end", "copy running-config startup-config",
    ],
    br1: [
      "interface g0/0", "no shutdown",
      "interface g0/0.10", "encapsulation dot1Q 10", "ip address 192.168.10.1 255.255.255.0", "ip nat inside",
      "interface g0/0.20", "encapsulation dot1Q 20", "ip address 192.168.20.1 255.255.255.0", "ip nat inside",
      "interface g0/0.99", "encapsulation dot1Q 99", "ip address 192.168.99.1 255.255.255.0",
      "interface g0/1", "ip address 10.0.0.2 255.255.255.252", "no shutdown",
      "interface g0/2", "ip address 203.0.113.2 255.255.255.252", "ip nat outside", "no shutdown", "exit",
      "ip dhcp excluded-address 192.168.10.1 192.168.10.20",
      "ip dhcp pool USERS", "network 192.168.10.0 255.255.255.0", "default-router 192.168.10.1", "dns-server 8.8.8.8", "exit",
      "router ospf 1", "network 10.0.0.0 0.0.0.3 area 0", "network 192.168.10.0 0.0.0.255 area 0", "network 192.168.20.0 0.0.0.255 area 0", "network 192.168.99.0 0.0.0.255 area 0",
      "passive-interface default", "no passive-interface g0/1", "exit",
      "ip route 0.0.0.0 0.0.0.0 203.0.113.1",
      "access-list 1 permit 192.168.10.0 0.0.0.255",
      "access-list 1 permit 192.168.20.0 0.0.0.255",
      "ip nat inside source list 1 interface g0/2 overload",
      "ip domain-name branch.lab",
      "username admin privilege 15 secret Br4nch!Adm1n",
      "crypto key generate rsa modulus 2048",
      "ip ssh version 2",
      "access-list 10 permit 192.168.99.0 0.0.0.255",
      "line vty 0 4", "login local", "transport input ssh", "access-class 10 in",
      "end", "copy running-config startup-config",
    ],
    user1: ["ipconfig /renew"],
    user2: ["ipconfig /renew"],
  },
  debrief: {
    en: "A branch is a stack of small jobs that depend on each other: VLANs and trunks before the subinterfaces can come up, routing before DHCP clients can go anywhere, OSPF so HQ knows the way back, and PAT only for the traffic that leaves through the ISP. Lock management down last, and test from both a permitted and a refused host so you know the ACL is doing the work. Then save, because none of it survives a reload otherwise.",
    hi: "Branch bahut saare chhote kaamon ka stack hai jo ek dusre par depend karte hain: subinterfaces tabhi up honge jab VLANs aur trunks ready hon, DHCP clients tabhi kahin jaa sakte hain jab routing ho, OSPF zaroori hai taaki HQ ko wapas aane ka raasta pata ho, aur PAT sirf us traffic ke liye jo ISP se bahar jaata hai. Management ko sabse aakhir mein lock karo, aur allowed aur refused dono hosts se test karo taaki pata chale ki ACL sach mein kaam kar raha hai. Phir save karo, warna reload ke baad kuch nahi bachega.",
  },
};

export default lab;
